### ISSUE TITLE
Label buttons are broken

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/forum#11]
Need to add a new view and/or change the link on this tab to make it not throw a 500 when clicked:

![code_for_america____forum](https://cloud.githubusercontent.com/assets/1957344/6657289/52b28556-cb04-11e4-8302-35845f603ea7.png)

leads to 

![octokit__notfound_at__forum_l_in_20progress](https://cloud.githubusercontent.com/assets/1957344/6657292/6c17b066-cb04-11e4-954e-ab5e9df51164.png)

**Comment by bsmithgall** [comment]
Also, a related issue would be to add emoji support :snowman: :icecream: :koala:

**Comment by daguar** [comment]
snofroala?
